name: Second Pipeline

on:
  push:
    branches: [ "main" ] 

jobs:
  Build_and_Push:
    runs-on: ubuntu-22.04

    steps:

    - name: Install Docker Compose and curlbackend_1.1.0
      run: |
        sudo apt update
        sudo apt install docker-compose curl -y        
    
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}  

    - name: pull docker images and run 
      run: |
        sudo docker pull sunidhi12/sunidhi_flaskapp:2.0
        sudo docker pull sunidhi12/sunidhi_ngnix:2.0
        sudo docker run -d sunidhi12/sunidhi_ngnix:2.0
        sudo docker run -d sunidhi12/sunidhi_ngnix:2.0
        
    - name: test app
      run: |
        curl  0.0.0.0:5000        
